name: Package_Install
on: [workflow_dispatch]

jobs:
 publish-gpr:
  runs-on: ubuntu-latest
  permissions:
   contents: read
   packages: write
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
      node-version: 16
      registry-url: https://npm.pkg.github.com
   - run: npm install @V2-org/package-without-repo --registry=https://npm.pkg.github.com
     env:
       NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
